all:
	g++ -Wall -c conecta4.h conecta4.cpp tresRaya.h tresRaya.cpp toqueFama.h toqueFama.cpp main.cpp
	g++ -Wall conecta4.o tresRaya.o toqueFama.o main.o -o juegosIce

clean:
	rm *.o juegosIce
list:
	ls
