all:
	g++ -g -Wall -c programaTicket.h programaTicket.cpp eventos.h eventos.cpp  password.h password.cpp main.cpp
	g++ -g -Wall programaTicket.o eventos.o password.cpp main.o -o tickets
clean:
	rm *.o *.gch
list:
	ls
